### ISSUE TITLE
Eine wilkommensnachicht mit bild und setup cmd

### ISSUE THREAD

**Issue by oa01** [TPP-01/ABV-Bot#8]
Ein command um einen channel zu definieren wo nachichten gesendet werden wenn wer joind mit nem bild

**Comment by EcstaticHades17** [comment]
Also basicaly ein dublikat der standart wilkommensnachricht...

**Comment by blockcrafter21** [comment]
nope

**Comment by blockcrafter21** [comment]
![image](https://user-images.githubusercontent.com/72599189/145570100-dd25cbe1-ecb0-42de-aeb7-e0aabec31329.png)
like this

**Comment by eum3l** [comment]
Mach ich noch diese Woche
